# Generated by Django 2.0 on 2019-01-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facts',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
