# Generated by Django 2.0 on 2019-01-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0004_facts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
